version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/painel-github"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      octokit:
        patterns:
          - "@octokit/*"
